version: "3"

services:
  server:
    build:
      context: .docker/php/8.1-apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

#  mysql:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_DATABASE}
#    ports:
#      - "3306:3306"
#    env_file:
#      - .env

  composer:
    image: composer/composer
    command:
      - composer install
    volumes:
      - ./:/app


###> doctrine/doctrine-bundle ###
  database:
#    image: postgres:${POSTGRES_VERSION:-14}-alpine
#    environment:
#      POSTGRES_DB: ${DB_DATABASE}
##      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_USER: ${DB_DATABASE}
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###
#
#volumes:
####> doctrine/doctrine-bundle ###
#  db-data:
###< doctrine/doctrine-bundle ###
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    env_file:
      - .env

